# Notebook 3 — Janelamento e Extração de Features

Terceiro estágio do pipeline. Lê os arquivos `_L1.npz` e produz, para cada paciente, nível de canais e partição (treino/teste), a matriz de features usada na classificação.

## Balanceamento das classes

O conjunto de treino é balanceado em proporção 1:1 entre pré-ictal e interictal; o conjunto de teste preserva a distribuição natural.

| Partição | Pré-ictal | Interictal | Justificativa |
|----------|-----------|------------|---------------|
| Treino | N janelas | N janelas amostradas | evita viés do classificador para a classe majoritária |
| Teste | todas | todas | distribuição realista, com métricas robustas a desbalanceamento |

No treino, dadas N janelas pré-ictais, amostram-se N janelas interictais distantes de crises, com distribuição estratificada no tempo de gravação (uma janela por faixa temporal) para refletir variabilidade circadiana. No teste não há reamostragem.

## Níveis de canais

A redução progressiva de eletrodos simula configurações compatíveis com dispositivos vestíveis.

| Nível | Canais | Quantidade | Datasets |
|-------|--------|------------|----------|
| R5 | fp1,fp2,f7,f3,fz,f4,f8,t3,t4,t5,t6,c3,c4,p3,p4 | 15 | CHB-MIT, Siena, Mendeley |
| R3 | f7,f3,fz,f4,f8,t3,t4,t5,t6,c3,c4 | 11 | CHB-MIT, Siena, Mendeley |
| R2 | f7,f3,fz,f4,f8,t3,t4,t5,t6 | 9 | CHB-MIT, Siena, Mendeley |
| R1 | t3,t4,t5,t6 | 4 | CHB-MIT, Siena, Mendeley |
| R0 | t3,t4 | 2 | CHB-MIT, Siena, Mendeley, SeizeIT2 |

## Features por canal

| Grupo | Features | Quantidade |
|-------|----------|------------|
| Temporais | desvio-padrão, variância, RMS, comprimento de linha, mobilidade de Hjorth, assimetria, curtose | 7 |
| Espectrais | potência em delta, theta, alpha, beta, gamma; entropia espectral; potência relativa em beta | 7 |
| Wavelet (DWT) | energia dos coeficientes de detalhe d1–d4 | 4 |
| Não-linear | complexidade de Hjorth | 1 |
| Total | | 19 |

## 1. Dependências e configuração

In [1]:
import os
os.environ['LOKY_MAX_CPU_COUNT'] = '4'

%pip install -q numpy pandas matplotlib scipy PyWavelets seaborn tqdm

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import re, glob, gc
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.signal import welch
from scipy.stats import skew, kurtosis
import pywt
from tqdm.auto import tqdm
import IPython.display as ipd

import warnings; warnings.filterwarnings('ignore')
np.random.seed(42)
sns.set_theme(style='whitegrid', palette='muted')

# Compatibilidade NumPy >= 2.0
if not hasattr(np, 'trapz'):
    np.trapz = np.trapezoid

ROOT_DIR   = 'data'
SIGNAL_DIR = os.path.join(ROOT_DIR, 'signals')
L1_DIR     = os.path.join(ROOT_DIR, 'level1_signals')
FEAT_DIR = os.path.join(ROOT_DIR, 'features')
LOG_DIR  = os.path.join(ROOT_DIR, 'logs'); os.makedirs(LOG_DIR, exist_ok=True)
for lv in ['R5', 'R3', 'R2', 'R1', 'R0']:
    os.makedirs(os.path.join(FEAT_DIR, lv, 'train'), exist_ok=True)
    os.makedirs(os.path.join(FEAT_DIR, lv, 'test'), exist_ok=True)

LBL = dict(interictal=0, preictal=1, ictal=2, postictal=3, unknown=-1)

# Janelamento
WIN_SEC = 30; STEP_TRAIN_SEC = 30; STEP_TEST_SEC = 15; MIN_PURITY = 0.80
# Balanceamento (interictal:preictal no treino)
BALANCE_RATIO_TRAIN = 1

BANDS = {'delta':(0.5,4),'theta':(4,8),'alpha':(8,13),'beta':(13,30),'gamma':(30,40)}

FEAT_NAMES = [
    'std','var','rms','line_len','mobility','skewness','kurtosis',
    'delta','theta','alpha','beta','gamma','sp_entropy','beta_rel',
    'dwt_d1','dwt_d2','dwt_d3','dwt_d4','complexity',
]
N_FEAT = len(FEAT_NAMES)
assert N_FEAT == 19

PATIENTS = {
    'CHBMIT'  : ['chb01','chb03','chb04','chb05','chb06','chb07','chb08','chb10','chb11','chb12','chb13','chb14'],
    'Siena'   : ['PN01','PN03','PN05','PN06','PN07','PN09','PN10','PN11','PN12','PN13','PN14','PN16'],
    'Mendeley': ['p10','p11','p12','p13','p14','p15'],
    'SeizeIT2': ['sub-001','sub-002','sub-003','sub-004','sub-005','sub-006','sub-007','sub-008','sub-009','sub-010','sub-011','sub-012'],
}
CHANNEL_SETS = {
    'R5': ['fp1','fp2','f7','f3','fz','f4','f8','t3','t4','t5','t6','c3','c4','p3','p4'],
    'R3': ['f7','f3','fz','f4','f8','t3','t4','t5','t6','c3','c4'],
    'R2': ['f7','f3','fz','f4','f8','t3','t4','t5','t6'],
    'R1': ['t3','t4','t5','t6'],
    'R0': ['t3','t4'],
}
LEVEL_DS = {
    'R5': ['CHBMIT','Siena','Mendeley'],
    'R3': ['CHBMIT','Siena','Mendeley'],
    'R2': ['CHBMIT','Siena','Mendeley'],
    'R1': ['CHBMIT','Siena','Mendeley'],
    'R0': ['CHBMIT','Siena','Mendeley','SeizeIT2'],
}
# Equivalência de nomenclatura entre datasets
CH_RENAME = {
    'CHBMIT': {'t7':'t3','t8':'t4','p7':'t5','p8':'t6'},
    'SeizeIT2': {'bteleftsd':'t3','bterightsd':'t4','crosstopsd':'t3'},
}
print('Configuração carregada.')
print(f'Janela {WIN_SEC} s | passo treino {STEP_TRAIN_SEC} s | passo teste {STEP_TEST_SEC} s')
print(f'Balanceamento de treino {BALANCE_RATIO_TRAIN}:1 (interictal:preictal)')
for lv, chs in CHANNEL_SETS.items():
    print(f'  {lv}: {len(chs):2d} canais x {N_FEAT} = {len(chs)*N_FEAT:4d} features | {", ".join(LEVEL_DS[lv])}')

Configuração carregada.
Janela 30 s | passo treino 30 s | passo teste 15 s
Balanceamento de treino 1:1 (interictal:preictal)
  R5: 15 canais x 19 =  285 features | CHBMIT, Siena, Mendeley
  R3: 11 canais x 19 =  209 features | CHBMIT, Siena, Mendeley
  R2:  9 canais x 19 =  171 features | CHBMIT, Siena, Mendeley
  R1:  4 canais x 19 =   76 features | CHBMIT, Siena, Mendeley
  R0:  2 canais x 19 =   38 features | CHBMIT, Siena, Mendeley, SeizeIT2

c:\Users\danil\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 2. Extração de features

`channel_feats` calcula as 19 features de um canal, na ordem de `FEAT_NAMES`. `build_fvec` concatena as features de todos os canais do nível; canais ausentes em um dataset são preenchidos com zeros, mantendo a dimensionalidade fixa.

In [3]:
def normalize_ch(name, rename_map=None):
    s = str(name).lower()
    for sub in ['eeg', '-ref', '-le', '-a1', '-a2', 'ref']:
        s = s.replace(sub, ' ')
    s = s.strip().replace(' ', '')
    if '-' in s:
        s = s.split('-')[0]
    s = re.sub(r'[^a-z0-9]', '', s)
    return rename_map.get(s, s) if rename_map else s

def channel_feats(sig, sfreq=256.0):
    '''19 features de um canal, na ordem de FEAT_NAMES.'''
    if len(sig) < 2:
        return np.zeros(N_FEAT, dtype=np.float32)
    d1 = np.diff(sig); d2 = np.diff(d1) if len(d1) > 1 else np.array([0.0])
    act = float(np.var(sig)); mob = float(np.sqrt(np.var(d1) / (act + 1e-10)))
    mob2 = float(np.sqrt(np.var(d2) / (np.var(d1) + 1e-10)))
    temporal = [float(np.std(sig)), act, float(np.sqrt(np.mean(sig**2))),
                float(np.sum(np.abs(d1))), mob, float(skew(sig)), float(kurtosis(sig))]
    nperseg = min(int(sfreq), max(int(sfreq // 2), len(sig) // 2)); nperseg = max(min(nperseg, len(sig)), 2)
    f, psd = welch(sig, fs=sfreq, nperseg=nperseg); total = psd.sum() + 1e-10
    bp = []
    for lo, hi in BANDS.values():
        idx = (f >= lo) & (f <= hi)
        bp.append(float(np.trapz(psd[idx], f[idx])) if idx.sum() > 1 else 0.0)
    pn = psd / total; pn = pn[pn > 0]; sp_ent = float(-np.sum(pn * np.log(pn)))
    b_idx = (f >= 13) & (f <= 30)
    beta_rel = float(np.trapz(psd[b_idx], f[b_idx]) / total) if b_idx.sum() > 1 else 0.0
    spectral = bp + [sp_ent, beta_rel]
    ml = min(4, pywt.dwt_max_level(len(sig), 'db4')) if len(sig) > 1 else 0
    if ml >= 1:
        coeffs = pywt.wavedec(sig.astype(np.float64), 'db4', level=ml)
        dwt = [float(np.sum(c**2)) for c in coeffs[1:5]]
        while len(dwt) < 4:
            dwt.append(0.0)
    else:
        dwt = [0.0] * 4
    complexity = mob2 / (mob + 1e-10)
    feat = np.array(temporal + spectral + dwt + [complexity], dtype=np.float32)
    assert len(feat) == N_FEAT
    return feat

def build_fvec(win_data, ch_names_raw, dataset, level):
    '''Concatena as features dos canais do nível; ausentes preenchidos com zeros.'''
    rename = CH_RENAME.get(dataset, {})
    ch_map = {normalize_ch(c, rename): i for i, c in enumerate(ch_names_raw)}
    parts = []
    for tgt in CHANNEL_SETS[level]:
        i = ch_map.get(tgt)
        parts.append(channel_feats(win_data[i].astype(np.float64)) if i is not None
                     else np.zeros(N_FEAT, dtype=np.float32))
    return np.concatenate(parts)

print('Funções de extração de features definidas.')
_t = channel_feats(np.random.randn(256 * 30).astype(np.float32), 256.0)
print(f'Verificação: channel_feats retornou {len(_t)} features.')

Funções de extração de features definidas.
Verificação: channel_feats retornou 19 features.

## 3. Janelamento

Cada janela de 30 s recebe a classe dominante (no mínimo `MIN_PURITY` das amostras). Apenas janelas interictais e pré-ictais são mantidas; ictal e pós-ictal não fazem parte da tarefa de predição. Para cada janela interictal registra-se o instante de início, usado na amostragem estratificada.

In [4]:
def extract_windows(dataset, patient, level, mode):
    '''Extrai janelas de todas as gravações de um paciente.
       Retorna (X_pre, X_inter, t_inter, n_arquivos).

    O sinal é carregado arquivo por arquivo e liberado imediatamente após
    o janelamento (del data + gc.collect). O pico de RAM é o maior arquivo
    individual do paciente.
    '''
    step_sec     = STEP_TRAIN_SEC if mode == 'train' else STEP_TEST_SEC
    files        = sorted(glob.glob(os.path.join(L1_DIR, f'{dataset}__{patient}__*_L1.npz')))
    n_feat_total = len(CHANNEL_SETS[level]) * N_FEAT
    X_pre, X_inter, t_inter = [], [], []
    global_t = 0.0

    for fp in files:
        # Carrega metadados leves do _L1.npz (sem sinal)
        try:
            z      = np.load(fp, allow_pickle=True)
            labels = z['labels']
            sfreq  = float(z['sfreq'])
            chs    = list(z['ch_names'])
            n      = int(z['n_samples'])
            z.close(); del z
        except Exception as e:
            tqdm.write(f'  {os.path.basename(fp)}: {e}'); continue

        # Carrega sinal do _signal.npz original
        sig_path = fp.replace(L1_DIR, SIGNAL_DIR).replace('_L1.npz', '_signal.npz')
        try:
            zs   = np.load(sig_path, allow_pickle=True)
            data = zs['data']          # float32, pico de RAM aqui
            zs.close(); del zs
        except Exception as e:
            tqdm.write(f'  {os.path.basename(sig_path)}: {e}')
            del labels; continue

        win_n  = int(WIN_SEC   * sfreq)
        step_n = max(1, int(step_sec * sfreq))

        for start in range(0, n - win_n + 1, step_n):
            wl    = labels[start:start + win_n]
            valid = wl[wl >= 0]
            if len(valid) == 0:
                continue
            vals, counts = np.unique(valid, return_counts=True)
            dom = vals[np.argmax(counts)]
            if dom not in (LBL['interictal'], LBL['preictal']):
                continue
            if counts.max() / win_n < MIN_PURITY:
                continue
            fv = build_fvec(data[:, start:start + win_n], chs, dataset, level)
            if dom == LBL['preictal']:
                X_pre.append(fv)
            else:
                X_inter.append(fv)
                t_inter.append(global_t + start / sfreq)

        global_t += n / sfreq
        del data, labels; gc.collect()   # libera sinal imediatamente

    return (np.array(X_pre,   dtype=np.float32) if X_pre   else np.empty((0, n_feat_total), dtype=np.float32),
            np.array(X_inter, dtype=np.float32) if X_inter else np.empty((0, n_feat_total), dtype=np.float32),
            np.array(t_inter, dtype=np.float64),
            len(files))

print('Função de janelamento definida.')

Função de janelamento definida.

## 4. Amostragem estratificada e montagem do conjunto

No treino, as N janelas interictais são amostradas dividindo o tempo de gravação em N faixas e tomando uma janela por faixa, o que evita concentração temporal. No teste, todas as janelas são mantidas.

In [5]:
def stratified_sample(X_inter, t_inter, n_target, seed=42):
    '''Amostra n_target janelas interictais distribuídas no tempo.'''
    n = len(X_inter)
    if n <= n_target:
        return X_inter
    rng = np.random.default_rng(seed)
    order = np.argsort(t_inter)
    bins = np.array_split(order, n_target)
    pick = [rng.choice(b) for b in bins if len(b) > 0]
    pick = np.array(pick[:n_target])
    return X_inter[np.sort(pick)]

def make_dataset(dataset, patient, level, mode):
    '''Monta (X, y). Treino: 1:1. Teste: distribuição natural.'''
    X_pre, X_inter, t_inter, n_files = extract_windows(dataset, patient, level, mode)
    n_pre = len(X_pre); n_inter_all = len(X_inter)
    if n_pre == 0:
        return None, None, dict(reason='sem janelas pré-ictais', n_files=n_files,
                                n_pre=0, n_inter=n_inter_all)
    if mode == 'train':
        n_target = n_pre * BALANCE_RATIO_TRAIN
        X_inter_s = stratified_sample(X_inter, t_inter, n_target, seed=42)
    else:
        X_inter_s = X_inter
    if len(X_inter_s) == 0:
        return None, None, dict(reason='sem janelas interictais', n_files=n_files,
                                n_pre=n_pre, n_inter=0)
    X = np.concatenate([X_inter_s, X_pre])
    y = np.concatenate([np.zeros(len(X_inter_s), dtype=np.int8),
                        np.ones(n_pre, dtype=np.int8)])
    info = dict(reason=None, n_files=n_files, n_pre=n_pre,
                n_inter_all=n_inter_all, n_inter_used=len(X_inter_s),
                ratio=round(len(X_inter_s) / max(n_pre, 1), 2))
    return X, y, info

def save_features(X, y, dataset, patient, level, mode):
    fname = os.path.join(FEAT_DIR, level, mode, f'{dataset}__{patient}.npz')
    np.savez_compressed(fname, X=X, y=y,
        feat_names=np.array(FEAT_NAMES), channels=np.array(CHANNEL_SETS[level]),
        dataset=np.str_(dataset), patient=np.str_(patient),
        level=np.str_(level), mode=np.str_(mode),
        win_sec=np.float32(WIN_SEC),
        step_sec=np.float32(STEP_TRAIN_SEC if mode == 'train' else STEP_TEST_SEC),
        n_feat_per_ch=np.int32(N_FEAT))
    return fname

print('Funções de amostragem e montagem definidas.')

Funções de amostragem e montagem definidas.

## 5. Extração

Percorre níveis, datasets, pacientes e partições. A gravação é incremental, permitindo retomada. Exclusões (paciente sem pré-ictal ou sem interictal em um nível) são registradas em log.

In [6]:
EXCLUSION_LOG = []; STATS = []

def run_extraction(dataset_filter=None):
    pending = []
    for lv, ds_list in LEVEL_DS.items():
        for ds in ds_list:
            if dataset_filter and ds != dataset_filter:
                continue
            for pat in PATIENTS[ds]:
                for mode in ['train', 'test']:
                    out = os.path.join(FEAT_DIR, lv, mode, f'{ds}__{pat}.npz')
                    if not os.path.exists(out):
                        pending.append((lv, ds, pat, mode, out))
    if not pending:
        print('Nada pendente.'); return
    print(f'Extraindo {len(pending)} tarefas.')
    pbar = tqdm(pending, desc='Extração', ncols=110)
    done = warn = 0
    for (lv, ds, pat, mode, out) in pbar:
        pbar.set_postfix_str(f'{lv}|{ds}|{pat}|{mode}')
        if os.path.exists(out):
            continue
        X, y, info = make_dataset(ds, pat, lv, mode)
        if X is None:
            EXCLUSION_LOG.append(dict(level=lv, dataset=ds, patient=pat, mode=mode, **info))
            tqdm.write(f'  excluído {lv}/{mode}/{ds}/{pat}: {info["reason"]}'); warn += 1; continue
        save_features(X, y, ds, pat, lv, mode)
        STATS.append(dict(level=lv, dataset=ds, patient=pat, mode=mode,
                          n_total=len(X), n_pre=int((y == 1).sum()),
                          n_inter=int((y == 0).sum()), ratio=info['ratio']))
        done += 1
        if mode == 'train':
            tqdm.write(f'  {lv}/{mode}/{ds}/{pat}: {len(X)} janelas '
                       f'(pré={info["n_pre"]}, inter={info["n_inter_used"]})')
    print(f'Extração concluída: {done} gravados | {warn} excluídos.')

run_extraction()

Extraindo 324 tarefas.

Extração:   0%|                                       | 1/324 [00:40<3:36:05, 40.14s/it, R5|CHBMIT|chb01|test]

  R5/train/CHBMIT/chb01: 314 janelas (pré=157, inter=157)

Extração:   1%|▎                                      | 3/324 [02:35<4:35:19, 51.46s/it, R5|CHBMIT|chb03|test]

  R5/train/CHBMIT/chb03: 240 janelas (pré=120, inter=120)

Extração:   2%|▌                                      | 5/324 [06:19<8:13:52, 92.89s/it, R5|CHBMIT|chb04|test]

  R5/train/CHBMIT/chb04: 214 janelas (pré=107, inter=107)

Extração:   2%|▊                                    | 7/324 [11:43<10:30:15, 119.29s/it, R5|CHBMIT|chb05|test]

  R5/train/CHBMIT/chb05: 208 janelas (pré=104, inter=104)

Extração:   3%|█                                    | 9/324 [16:10<11:34:49, 132.35s/it, R5|CHBMIT|chb06|test]

  R5/train/CHBMIT/chb06: 424 janelas (pré=212, inter=212)

Extração:   3%|█▏                                  | 11/324 [24:49<16:24:41, 188.76s/it, R5|CHBMIT|chb07|test]

  R5/train/CHBMIT/chb07: 158 janelas (pré=79, inter=79)

Extração:   4%|█▍                                  | 13/324 [30:12<14:08:29, 163.70s/it, R5|CHBMIT|chb08|test]

  R5/train/CHBMIT/chb08: 262 janelas (pré=131, inter=131)

Extração:   5%|█▋                                  | 15/324 [32:56<10:31:50, 122.69s/it, R5|CHBMIT|chb10|test]

  R5/train/CHBMIT/chb10: 366 janelas (pré=183, inter=183)

Extração:   5%|█▉                                   | 17/324 [36:23<9:06:28, 106.80s/it, R5|CHBMIT|chb11|test]

  R5/train/CHBMIT/chb11: 106 janelas (pré=53, inter=53)

Extração:   6%|██▏                                   | 19/324 [38:19<6:52:17, 81.11s/it, R5|CHBMIT|chb12|test]

  R5/train/CHBMIT/chb12: 612 janelas (pré=306, inter=306)

Extração:   6%|██▍                                   | 21/324 [40:28<5:57:22, 70.77s/it, R5|CHBMIT|chb13|test]

  R5/train/CHBMIT/chb13: 378 janelas (pré=189, inter=189)

Extração:   7%|██▋                                   | 23/324 [42:32<5:24:25, 64.67s/it, R5|CHBMIT|chb14|test]

  R5/train/CHBMIT/chb14: 416 janelas (pré=208, inter=208)

Extração:   8%|███                                     | 25/324 [44:33<5:03:38, 60.93s/it, R5|Siena|PN01|test]

  R5/train/Siena/PN01: 104 janelas (pré=52, inter=52)

Extração:   8%|███▎                                    | 27/324 [46:58<5:26:12, 65.90s/it, R5|Siena|PN03|test]

  R5/train/Siena/PN03: 54 janelas (pré=27, inter=27)

Extração:   9%|███▌                                    | 29/324 [49:11<5:01:55, 61.41s/it, R5|Siena|PN05|test]

  R5/train/Siena/PN05: 158 janelas (pré=79, inter=79)

Extração:  10%|███▊                                    | 31/324 [49:52<3:17:50, 40.51s/it, R5|Siena|PN06|test]

  R5/train/Siena/PN06: 208 janelas (pré=104, inter=104)

Extração:  10%|████                                    | 33/324 [50:55<2:52:57, 35.66s/it, R5|Siena|PN07|test]

  R5/train/Siena/PN07: 52 janelas (pré=26, inter=26)

Extração:  11%|████▎                                   | 35/324 [52:05<2:41:56, 33.62s/it, R5|Siena|PN09|test]

  R5/train/Siena/PN09: 156 janelas (pré=78, inter=78)

Extração:  11%|████▌                                   | 37/324 [53:15<2:44:40, 34.43s/it, R5|Siena|PN10|test]

  R5/train/Siena/PN10: 476 janelas (pré=238, inter=238)

Extração:  12%|████▊                                   | 39/324 [54:26<2:34:10, 32.46s/it, R5|Siena|PN11|test]

  R5/train/Siena/PN11: 54 janelas (pré=27, inter=27)

Extração:  13%|█████                                   | 41/324 [54:53<1:48:19, 22.97s/it, R5|Siena|PN12|test]

  R5/train/Siena/PN12: 136 janelas (pré=68, inter=68)

Extração:  13%|█████▎                                  | 43/324 [55:38<1:45:07, 22.45s/it, R5|Siena|PN13|test]

  R5/train/Siena/PN13: 156 janelas (pré=78, inter=78)

Extração:  14%|█████▌                                  | 45/324 [57:16<2:52:32, 37.10s/it, R5|Siena|PN14|test]

  R5/train/Siena/PN14: 210 janelas (pré=105, inter=105)

Extração:  15%|█████▊                                  | 47/324 [59:23<3:33:00, 46.14s/it, R5|Siena|PN16|test]

  R5/train/Siena/PN16: 106 janelas (pré=53, inter=53)

Extração:  15%|█████▋                                | 49/324 [59:58<2:21:25, 30.85s/it, R5|Mendeley|p10|test]

  R5/train/Mendeley/p10: 108 janelas (pré=54, inter=54)

Extração:  16%|█████▋                              | 51/324 [1:00:37<1:54:30, 25.17s/it, R5|Mendeley|p11|test]

  R5/train/Mendeley/p11: 366 janelas (pré=183, inter=183)

Extração:  16%|█████▉                              | 53/324 [1:01:22<1:44:23, 23.11s/it, R5|Mendeley|p12|test]

  R5/train/Mendeley/p12: 320 janelas (pré=160, inter=160)

Extração:  17%|██████                              | 55/324 [1:02:06<1:39:23, 22.17s/it, R5|Mendeley|p13|test]

  R5/train/Mendeley/p13: 318 janelas (pré=159, inter=159)

Extração:  18%|██████▎                             | 57/324 [1:02:48<1:31:13, 20.50s/it, R5|Mendeley|p14|test]

  R5/train/Mendeley/p14: 223 janelas (pré=183, inter=40)

Extração:  18%|██████▌                             | 59/324 [1:03:28<1:30:22, 20.46s/it, R5|Mendeley|p15|test]

  R5/train/Mendeley/p15: 262 janelas (pré=131, inter=131)

Extração:  19%|██████▊                             | 61/324 [1:04:37<2:00:09, 27.41s/it, R3|CHBMIT|chb01|test]

  R3/train/CHBMIT/chb01: 314 janelas (pré=157, inter=157)

Extração:  19%|███████                             | 63/324 [1:06:10<2:36:49, 36.05s/it, R3|CHBMIT|chb03|test]

  R3/train/CHBMIT/chb03: 240 janelas (pré=120, inter=120)

Extração:  20%|███████▏                            | 65/324 [1:09:08<4:44:27, 65.90s/it, R3|CHBMIT|chb04|test]

  R3/train/CHBMIT/chb04: 214 janelas (pré=107, inter=107)

Extração:  21%|███████▍                            | 67/324 [1:13:11<6:08:04, 85.93s/it, R3|CHBMIT|chb05|test]

  R3/train/CHBMIT/chb05: 208 janelas (pré=104, inter=104)

Extração:  21%|███████▋                            | 69/324 [1:16:38<7:01:10, 99.10s/it, R3|CHBMIT|chb06|test]

  R3/train/CHBMIT/chb06: 424 janelas (pré=212, inter=212)

Extração:  22%|███████▋                           | 71/324 [1:23:09<9:58:36, 141.96s/it, R3|CHBMIT|chb07|test]

  R3/train/CHBMIT/chb07: 158 janelas (pré=79, inter=79)

Extração:  23%|███████▉                           | 73/324 [1:27:09<8:32:45, 122.57s/it, R3|CHBMIT|chb08|test]

  R3/train/CHBMIT/chb08: 262 janelas (pré=131, inter=131)

Extração:  23%|████████▎                           | 75/324 [1:29:14<6:24:23, 92.62s/it, R3|CHBMIT|chb10|test]

  R3/train/CHBMIT/chb10: 366 janelas (pré=183, inter=183)

Extração:  24%|████████▌                           | 77/324 [1:31:48<5:30:09, 80.20s/it, R3|CHBMIT|chb11|test]

  R3/train/CHBMIT/chb11: 106 janelas (pré=53, inter=53)

Extração:  24%|████████▊                           | 79/324 [1:33:17<4:10:53, 61.44s/it, R3|CHBMIT|chb12|test]

  R3/train/CHBMIT/chb12: 612 janelas (pré=306, inter=306)

Extração:  25%|█████████                           | 81/324 [1:34:56<3:38:41, 54.00s/it, R3|CHBMIT|chb13|test]

  R3/train/CHBMIT/chb13: 378 janelas (pré=189, inter=189)

Extração:  26%|█████████▏                          | 83/324 [1:36:28<3:15:31, 48.68s/it, R3|CHBMIT|chb14|test]

  R3/train/CHBMIT/chb14: 416 janelas (pré=208, inter=208)

Extração:  26%|█████████▉                            | 85/324 [1:38:01<3:05:15, 46.51s/it, R3|Siena|PN01|test]

  R3/train/Siena/PN01: 104 janelas (pré=52, inter=52)

Extração:  27%|██████████▏                           | 87/324 [1:39:49<3:16:27, 49.74s/it, R3|Siena|PN03|test]

  R3/train/Siena/PN03: 54 janelas (pré=27, inter=27)

Extração:  27%|██████████▍                           | 89/324 [1:41:28<3:00:18, 46.04s/it, R3|Siena|PN05|test]

  R3/train/Siena/PN05: 158 janelas (pré=79, inter=79)

Extração:  28%|██████████▋                           | 91/324 [1:42:00<1:59:18, 30.72s/it, R3|Siena|PN06|test]

  R3/train/Siena/PN06: 208 janelas (pré=104, inter=104)

Extração:  29%|██████████▉                           | 93/324 [1:42:47<1:43:45, 26.95s/it, R3|Siena|PN07|test]

  R3/train/Siena/PN07: 52 janelas (pré=26, inter=26)

Extração:  29%|███████████▏                          | 95/324 [1:43:42<1:39:24, 26.05s/it, R3|Siena|PN09|test]

  R3/train/Siena/PN09: 156 janelas (pré=78, inter=78)

Extração:  30%|███████████▍                          | 97/324 [1:44:38<1:43:09, 27.27s/it, R3|Siena|PN10|test]

  R3/train/Siena/PN10: 476 janelas (pré=238, inter=238)

Extração:  31%|███████████▌                          | 99/324 [1:45:32<1:34:20, 25.16s/it, R3|Siena|PN11|test]

  R3/train/Siena/PN11: 54 janelas (pré=27, inter=27)

Extração:  31%|███████████▌                         | 101/324 [1:45:52<1:05:32, 17.63s/it, R3|Siena|PN12|test]

  R3/train/Siena/PN12: 136 janelas (pré=68, inter=68)

Extração:  32%|███████████▊                         | 103/324 [1:46:28<1:04:25, 17.49s/it, R3|Siena|PN13|test]

  R3/train/Siena/PN13: 156 janelas (pré=78, inter=78)

Extração:  32%|███████████▉                         | 105/324 [1:47:40<1:42:26, 28.07s/it, R3|Siena|PN14|test]

  R3/train/Siena/PN14: 210 janelas (pré=105, inter=105)

Extração:  33%|████████████▏                        | 107/324 [1:49:16<2:06:05, 34.86s/it, R3|Siena|PN16|test]

  R3/train/Siena/PN16: 106 janelas (pré=53, inter=53)

Extração:  34%|███████████▊                       | 109/324 [1:49:43<1:24:04, 23.46s/it, R3|Mendeley|p10|test]

  R3/train/Mendeley/p10: 108 janelas (pré=54, inter=54)

Extração:  34%|███████████▉                       | 111/324 [1:50:11<1:06:29, 18.73s/it, R3|Mendeley|p11|test]

  R3/train/Mendeley/p11: 366 janelas (pré=183, inter=183)

Extração:  35%|████████████▏                      | 113/324 [1:50:45<1:00:44, 17.27s/it, R3|Mendeley|p12|test]

  R3/train/Mendeley/p12: 320 janelas (pré=160, inter=160)

Extração:  35%|█████████████▏                       | 115/324 [1:51:18<57:37, 16.54s/it, R3|Mendeley|p13|test]

  R3/train/Mendeley/p13: 318 janelas (pré=159, inter=159)

Extração:  36%|█████████████▎                       | 117/324 [1:51:49<53:22, 15.47s/it, R3|Mendeley|p14|test]

  R3/train/Mendeley/p14: 223 janelas (pré=183, inter=40)

Extração:  37%|█████████████▌                       | 119/324 [1:52:19<52:20, 15.32s/it, R3|Mendeley|p15|test]

  R3/train/Mendeley/p15: 262 janelas (pré=131, inter=131)

Extração:  37%|█████████████                      | 121/324 [1:53:14<1:12:47, 21.51s/it, R2|CHBMIT|chb01|test]

  R2/train/CHBMIT/chb01: 314 janelas (pré=157, inter=157)

Extração:  38%|█████████████▎                     | 123/324 [1:54:29<1:36:36, 28.84s/it, R2|CHBMIT|chb03|test]

  R2/train/CHBMIT/chb03: 240 janelas (pré=120, inter=120)

Extração:  39%|█████████████▌                     | 125/324 [1:56:55<2:57:35, 53.54s/it, R2|CHBMIT|chb04|test]

  R2/train/CHBMIT/chb04: 214 janelas (pré=107, inter=107)

Extração:  39%|█████████████▋                     | 127/324 [2:00:17<3:53:14, 71.04s/it, R2|CHBMIT|chb05|test]

  R2/train/CHBMIT/chb05: 208 janelas (pré=104, inter=104)

Extração:  40%|█████████████▉                     | 129/324 [2:03:08<4:26:26, 81.98s/it, R2|CHBMIT|chb06|test]

  R2/train/CHBMIT/chb06: 424 janelas (pré=212, inter=212)

Extração:  40%|█████████████▋                    | 131/324 [2:08:28<6:13:13, 116.03s/it, R2|CHBMIT|chb07|test]

  R2/train/CHBMIT/chb07: 158 janelas (pré=79, inter=79)

Extração:  41%|█████████████▉                    | 133/324 [2:11:47<5:21:01, 100.84s/it, R2|CHBMIT|chb08|test]

  R2/train/CHBMIT/chb08: 262 janelas (pré=131, inter=131)

Extração:  42%|██████████████▌                    | 135/324 [2:13:32<4:01:40, 76.72s/it, R2|CHBMIT|chb10|test]

  R2/train/CHBMIT/chb10: 366 janelas (pré=183, inter=183)

Extração:  42%|██████████████▊                    | 137/324 [2:15:39<3:27:13, 66.49s/it, R2|CHBMIT|chb11|test]

  R2/train/CHBMIT/chb11: 106 janelas (pré=53, inter=53)

Extração:  43%|███████████████                    | 139/324 [2:16:55<2:38:54, 51.54s/it, R2|CHBMIT|chb12|test]

  R2/train/CHBMIT/chb12: 612 janelas (pré=306, inter=306)

Extração:  44%|███████████████▏                   | 141/324 [2:18:19<2:18:46, 45.50s/it, R2|CHBMIT|chb13|test]

  R2/train/CHBMIT/chb13: 378 janelas (pré=189, inter=189)

Extração:  44%|███████████████▍                   | 143/324 [2:19:36<2:04:09, 41.16s/it, R2|CHBMIT|chb14|test]

  R2/train/CHBMIT/chb14: 416 janelas (pré=208, inter=208)

Extração:  45%|████████████████▌                    | 145/324 [2:20:55<1:57:09, 39.27s/it, R2|Siena|PN01|test]

  R2/train/Siena/PN01: 104 janelas (pré=52, inter=52)

Extração:  45%|████████████████▊                    | 147/324 [2:22:26<2:03:42, 41.93s/it, R2|Siena|PN03|test]

  R2/train/Siena/PN03: 54 janelas (pré=27, inter=27)

Extração:  46%|█████████████████                    | 149/324 [2:23:48<1:52:43, 38.65s/it, R2|Siena|PN05|test]

  R2/train/Siena/PN05: 158 janelas (pré=79, inter=79)

Extração:  47%|█████████████████▏                   | 151/324 [2:24:16<1:15:07, 26.05s/it, R2|Siena|PN06|test]

  R2/train/Siena/PN06: 208 janelas (pré=104, inter=104)

Extração:  47%|█████████████████▍                   | 153/324 [2:24:57<1:05:25, 22.96s/it, R2|Siena|PN07|test]

  R2/train/Siena/PN07: 52 janelas (pré=26, inter=26)

Extração:  48%|█████████████████▋                   | 155/324 [2:25:41<1:00:51, 21.60s/it, R2|Siena|PN09|test]

  R2/train/Siena/PN09: 156 janelas (pré=78, inter=78)

Extração:  48%|█████████████████▉                   | 157/324 [2:26:28<1:03:19, 22.75s/it, R2|Siena|PN10|test]

  R2/train/Siena/PN10: 476 janelas (pré=238, inter=238)

Extração:  49%|███████████████████▏                   | 159/324 [2:27:14<58:10, 21.15s/it, R2|Siena|PN11|test]

  R2/train/Siena/PN11: 54 janelas (pré=27, inter=27)

Extração:  50%|███████████████████▍                   | 161/324 [2:27:31<40:30, 14.91s/it, R2|Siena|PN12|test]

  R2/train/Siena/PN12: 136 janelas (pré=68, inter=68)

Extração:  50%|███████████████████▌                   | 163/324 [2:28:01<39:13, 14.62s/it, R2|Siena|PN13|test]

  R2/train/Siena/PN13: 156 janelas (pré=78, inter=78)

Extração:  51%|██████████████████▊                  | 165/324 [2:29:04<1:04:23, 24.30s/it, R2|Siena|PN14|test]

  R2/train/Siena/PN14: 210 janelas (pré=105, inter=105)

Extração:  52%|███████████████████                  | 167/324 [2:30:23<1:16:57, 29.41s/it, R2|Siena|PN16|test]

  R2/train/Siena/PN16: 106 janelas (pré=53, inter=53)

Extração:  52%|███████████████████▎                 | 169/324 [2:30:46<51:06, 19.79s/it, R2|Mendeley|p10|test]

  R2/train/Mendeley/p10: 108 janelas (pré=54, inter=54)

Extração:  53%|███████████████████▌                 | 171/324 [2:31:10<40:24, 15.84s/it, R2|Mendeley|p11|test]

  R2/train/Mendeley/p11: 366 janelas (pré=183, inter=183)

Extração:  53%|███████████████████▊                 | 173/324 [2:31:39<36:56, 14.68s/it, R2|Mendeley|p12|test]

  R2/train/Mendeley/p12: 320 janelas (pré=160, inter=160)

Extração:  54%|███████████████████▉                 | 175/324 [2:32:08<35:33, 14.32s/it, R2|Mendeley|p13|test]

  R2/train/Mendeley/p13: 318 janelas (pré=159, inter=159)

Extração:  55%|████████████████████▏                | 177/324 [2:32:35<32:47, 13.39s/it, R2|Mendeley|p14|test]

  R2/train/Mendeley/p14: 223 janelas (pré=183, inter=40)

Extração:  55%|████████████████████▍                | 179/324 [2:33:00<31:40, 13.10s/it, R2|Mendeley|p15|test]

  R2/train/Mendeley/p15: 262 janelas (pré=131, inter=131)

Extração:  56%|████████████████████▋                | 181/324 [2:33:39<38:30, 16.15s/it, R1|CHBMIT|chb01|test]

  R1/train/CHBMIT/chb01: 314 janelas (pré=157, inter=157)

Extração:  56%|████████████████████▉                | 183/324 [2:34:21<42:29, 18.08s/it, R1|CHBMIT|chb03|test]

  R1/train/CHBMIT/chb03: 240 janelas (pré=120, inter=120)

Extração:  57%|███████████████████▉               | 185/324 [2:35:40<1:10:25, 30.40s/it, R1|CHBMIT|chb04|test]

  R1/train/CHBMIT/chb04: 214 janelas (pré=107, inter=107)

Extração:  58%|████████████████████▏              | 187/324 [2:37:24<1:26:44, 37.99s/it, R1|CHBMIT|chb05|test]

  R1/train/CHBMIT/chb05: 208 janelas (pré=104, inter=104)

Extração:  58%|████████████████████▍              | 189/324 [2:39:00<1:41:54, 45.29s/it, R1|CHBMIT|chb06|test]

  R1/train/CHBMIT/chb06: 424 janelas (pré=212, inter=212)

Extração:  59%|████████████████████▋              | 191/324 [2:41:49<2:18:30, 62.49s/it, R1|CHBMIT|chb07|test]

  R1/train/CHBMIT/chb07: 158 janelas (pré=79, inter=79)

Extração:  60%|████████████████████▊              | 193/324 [2:43:31<1:56:42, 53.46s/it, R1|CHBMIT|chb08|test]

  R1/train/CHBMIT/chb08: 262 janelas (pré=131, inter=131)

Extração:  60%|█████████████████████              | 195/324 [2:44:30<1:29:47, 41.77s/it, R1|CHBMIT|chb10|test]

  R1/train/CHBMIT/chb10: 366 janelas (pré=183, inter=183)

Extração:  61%|█████████████████████▎             | 197/324 [2:45:38<1:16:02, 35.92s/it, R1|CHBMIT|chb11|test]

  R1/train/CHBMIT/chb11: 106 janelas (pré=53, inter=53)

Extração:  61%|██████████████████████▋              | 199/324 [2:46:20<59:00, 28.32s/it, R1|CHBMIT|chb12|test]

  R1/train/CHBMIT/chb12: 612 janelas (pré=306, inter=306)

Extração:  62%|██████████████████████▉              | 201/324 [2:47:08<52:19, 25.53s/it, R1|CHBMIT|chb13|test]

  R1/train/CHBMIT/chb13: 378 janelas (pré=189, inter=189)

Extração:  63%|███████████████████████▏             | 203/324 [2:47:51<46:33, 23.09s/it, R1|CHBMIT|chb14|test]

  R1/train/CHBMIT/chb14: 416 janelas (pré=208, inter=208)

Extração:  63%|████████████████████████▋              | 205/324 [2:48:34<43:28, 21.92s/it, R1|Siena|PN01|test]

  R1/train/Siena/PN01: 104 janelas (pré=52, inter=52)

Extração:  64%|████████████████████████▉              | 207/324 [2:49:24<45:16, 23.21s/it, R1|Siena|PN03|test]

  R1/train/Siena/PN03: 54 janelas (pré=27, inter=27)

Extração:  65%|█████████████████████████▏             | 209/324 [2:50:08<40:37, 21.20s/it, R1|Siena|PN05|test]

  R1/train/Siena/PN05: 158 janelas (pré=79, inter=79)

Extração:  65%|█████████████████████████▍             | 211/324 [2:50:25<28:03, 14.90s/it, R1|Siena|PN06|test]

  R1/train/Siena/PN06: 208 janelas (pré=104, inter=104)

Extração:  66%|█████████████████████████▋             | 213/324 [2:50:49<24:37, 13.31s/it, R1|Siena|PN07|test]

  R1/train/Siena/PN07: 52 janelas (pré=26, inter=26)

Extração:  66%|█████████████████████████▉             | 215/324 [2:51:14<22:21, 12.31s/it, R1|Siena|PN09|test]

  R1/train/Siena/PN09: 156 janelas (pré=78, inter=78)

Extração:  67%|██████████████████████████             | 217/324 [2:51:42<24:04, 13.50s/it, R1|Siena|PN10|test]

  R1/train/Siena/PN10: 476 janelas (pré=238, inter=238)

Extração:  68%|██████████████████████████▎            | 219/324 [2:52:09<21:50, 12.48s/it, R1|Siena|PN11|test]

  R1/train/Siena/PN11: 54 janelas (pré=27, inter=27)

Extração:  68%|██████████████████████████▌            | 221/324 [2:52:19<15:10,  8.84s/it, R1|Siena|PN12|test]

  R1/train/Siena/PN12: 136 janelas (pré=68, inter=68)

Extração:  69%|██████████████████████████▊            | 223/324 [2:52:37<14:55,  8.87s/it, R1|Siena|PN13|test]

  R1/train/Siena/PN13: 156 janelas (pré=78, inter=78)

Extração:  69%|███████████████████████████            | 225/324 [2:53:14<23:38, 14.32s/it, R1|Siena|PN14|test]

  R1/train/Siena/PN14: 210 janelas (pré=105, inter=105)

Extração:  70%|███████████████████████████▎           | 227/324 [2:53:57<26:47, 16.57s/it, R1|Siena|PN16|test]

  R1/train/Siena/PN16: 106 janelas (pré=53, inter=53)

Extração:  71%|██████████████████████████▏          | 229/324 [2:54:10<17:41, 11.17s/it, R1|Mendeley|p10|test]

  R1/train/Mendeley/p10: 108 janelas (pré=54, inter=54)

Extração:  71%|██████████████████████████▍          | 231/324 [2:54:24<14:15,  9.20s/it, R1|Mendeley|p11|test]

  R1/train/Mendeley/p11: 366 janelas (pré=183, inter=183)

Extração:  72%|██████████████████████████▌          | 233/324 [2:54:41<13:07,  8.65s/it, R1|Mendeley|p12|test]

  R1/train/Mendeley/p12: 320 janelas (pré=160, inter=160)

Extração:  73%|██████████████████████████▊          | 235/324 [2:54:58<12:35,  8.48s/it, R1|Mendeley|p13|test]

  R1/train/Mendeley/p13: 318 janelas (pré=159, inter=159)

Extração:  73%|███████████████████████████          | 237/324 [2:55:15<11:41,  8.06s/it, R1|Mendeley|p14|test]

  R1/train/Mendeley/p14: 223 janelas (pré=183, inter=40)

Extração:  74%|███████████████████████████▎         | 239/324 [2:55:30<11:26,  8.07s/it, R1|Mendeley|p15|test]

  R1/train/Mendeley/p15: 262 janelas (pré=131, inter=131)

Extração:  74%|███████████████████████████▌         | 241/324 [2:55:56<14:19, 10.36s/it, R0|CHBMIT|chb01|test]

  R0/train/CHBMIT/chb01: 314 janelas (pré=157, inter=157)

Extração:  75%|███████████████████████████▊         | 243/324 [2:56:25<16:41, 12.36s/it, R0|CHBMIT|chb03|test]

  R0/train/CHBMIT/chb03: 240 janelas (pré=120, inter=120)

Extração:  76%|███████████████████████████▉         | 245/324 [2:57:18<27:00, 20.52s/it, R0|CHBMIT|chb04|test]

  R0/train/CHBMIT/chb04: 214 janelas (pré=107, inter=107)

Extração:  76%|████████████████████████████▏        | 247/324 [2:58:23<31:43, 24.71s/it, R0|CHBMIT|chb05|test]

  R0/train/CHBMIT/chb05: 208 janelas (pré=104, inter=104)

Extração:  77%|████████████████████████████▍        | 249/324 [2:59:28<37:42, 30.17s/it, R0|CHBMIT|chb06|test]

  R0/train/CHBMIT/chb06: 424 janelas (pré=212, inter=212)

Extração:  77%|████████████████████████████▋        | 251/324 [3:01:15<49:13, 40.46s/it, R0|CHBMIT|chb07|test]

  R0/train/CHBMIT/chb07: 158 janelas (pré=79, inter=79)

Extração:  78%|████████████████████████████▉        | 253/324 [3:02:19<40:38, 34.34s/it, R0|CHBMIT|chb08|test]

  R0/train/CHBMIT/chb08: 262 janelas (pré=131, inter=131)

Extração:  79%|█████████████████████████████        | 255/324 [3:02:59<31:29, 27.38s/it, R0|CHBMIT|chb10|test]

  R0/train/CHBMIT/chb10: 366 janelas (pré=183, inter=183)

Extração:  79%|█████████████████████████████▎       | 257/324 [3:03:43<26:14, 23.49s/it, R0|CHBMIT|chb11|test]

  R0/train/CHBMIT/chb11: 106 janelas (pré=53, inter=53)

Extração:  80%|█████████████████████████████▌       | 259/324 [3:04:12<20:35, 19.01s/it, R0|CHBMIT|chb12|test]

  R0/train/CHBMIT/chb12: 612 janelas (pré=306, inter=306)

Extração:  81%|█████████████████████████████▊       | 261/324 [3:04:45<18:06, 17.25s/it, R0|CHBMIT|chb13|test]

  R0/train/CHBMIT/chb13: 378 janelas (pré=189, inter=189)

Extração:  81%|██████████████████████████████       | 263/324 [3:05:14<15:54, 15.65s/it, R0|CHBMIT|chb14|test]

  R0/train/CHBMIT/chb14: 416 janelas (pré=208, inter=208)

Extração:  82%|███████████████████████████████▉       | 265/324 [3:05:44<14:49, 15.08s/it, R0|Siena|PN01|test]

  R0/train/Siena/PN01: 104 janelas (pré=52, inter=52)

Extração:  82%|████████████████████████████████▏      | 267/324 [3:06:17<15:04, 15.87s/it, R0|Siena|PN03|test]

  R0/train/Siena/PN03: 54 janelas (pré=27, inter=27)

Extração:  83%|████████████████████████████████▍      | 269/324 [3:06:45<12:55, 14.10s/it, R0|Siena|PN05|test]

  R0/train/Siena/PN05: 158 janelas (pré=79, inter=79)

Extração:  84%|████████████████████████████████▌      | 271/324 [3:06:58<09:07, 10.32s/it, R0|Siena|PN06|test]

  R0/train/Siena/PN06: 208 janelas (pré=104, inter=104)

Extração:  84%|████████████████████████████████▊      | 273/324 [3:07:15<07:57,  9.36s/it, R0|Siena|PN07|test]

  R0/train/Siena/PN07: 52 janelas (pré=26, inter=26)

Extração:  85%|█████████████████████████████████      | 275/324 [3:07:32<07:04,  8.67s/it, R0|Siena|PN09|test]

  R0/train/Siena/PN09: 156 janelas (pré=78, inter=78)

Extração:  85%|█████████████████████████████████▎     | 277/324 [3:07:54<07:45,  9.90s/it, R0|Siena|PN10|test]

  R0/train/Siena/PN10: 476 janelas (pré=238, inter=238)

Extração:  86%|█████████████████████████████████▌     | 279/324 [3:08:13<06:48,  9.07s/it, R0|Siena|PN11|test]

  R0/train/Siena/PN11: 54 janelas (pré=27, inter=27)

Extração:  87%|█████████████████████████████████▊     | 281/324 [3:08:20<04:38,  6.49s/it, R0|Siena|PN12|test]

  R0/train/Siena/PN12: 136 janelas (pré=68, inter=68)

Extração:  87%|██████████████████████████████████     | 283/324 [3:08:34<04:31,  6.63s/it, R0|Siena|PN13|test]

  R0/train/Siena/PN13: 156 janelas (pré=78, inter=78)

Extração:  88%|██████████████████████████████████▎    | 285/324 [3:09:00<06:42, 10.32s/it, R0|Siena|PN14|test]

  R0/train/Siena/PN14: 210 janelas (pré=105, inter=105)

Extração:  89%|██████████████████████████████████▌    | 287/324 [3:09:29<07:01, 11.39s/it, R0|Siena|PN16|test]

  R0/train/Siena/PN16: 106 janelas (pré=53, inter=53)

Extração:  89%|█████████████████████████████████    | 289/324 [3:09:37<04:29,  7.70s/it, R0|Mendeley|p10|test]

  R0/train/Mendeley/p10: 108 janelas (pré=54, inter=54)

Extração:  90%|█████████████████████████████████▏   | 291/324 [3:09:48<03:34,  6.51s/it, R0|Mendeley|p11|test]

  R0/train/Mendeley/p11: 366 janelas (pré=183, inter=183)

Extração:  90%|█████████████████████████████████▍   | 293/324 [3:10:00<03:13,  6.25s/it, R0|Mendeley|p12|test]

  R0/train/Mendeley/p12: 320 janelas (pré=160, inter=160)

Extração:  91%|█████████████████████████████████▋   | 295/324 [3:10:13<03:00,  6.22s/it, R0|Mendeley|p13|test]

  R0/train/Mendeley/p13: 318 janelas (pré=159, inter=159)

Extração:  92%|█████████████████████████████████▉   | 297/324 [3:10:25<02:42,  6.01s/it, R0|Mendeley|p14|test]

  R0/train/Mendeley/p14: 223 janelas (pré=183, inter=40)

Extração:  92%|██████████████████████████████████▏  | 299/324 [3:10:37<02:32,  6.10s/it, R0|Mendeley|p15|test]

  R0/train/Mendeley/p15: 262 janelas (pré=131, inter=131)

Extração:  93%|██████████████████████████████▋  | 301/324 [3:11:17<05:23, 14.08s/it, R0|SeizeIT2|sub-001|test]

  R0/train/SeizeIT2/sub-001: 210 janelas (pré=105, inter=105)

Extração:  94%|██████████████████████████████▊  | 303/324 [3:12:38<09:13, 26.34s/it, R0|SeizeIT2|sub-002|test]

  R0/train/SeizeIT2/sub-002: 752 janelas (pré=376, inter=376)

Extração:  94%|███████████████████████████████  | 305/324 [3:14:00<10:34, 33.38s/it, R0|SeizeIT2|sub-003|test]

  R0/train/SeizeIT2/sub-003: 54 janelas (pré=27, inter=27)

Extração:  95%|███████████████████████████████▎ | 307/324 [3:15:14<09:09, 32.31s/it, R0|SeizeIT2|sub-004|test]

  R0/train/SeizeIT2/sub-004: 208 janelas (pré=104, inter=104)

Extração:  95%|███████████████████████████████▍ | 309/324 [3:15:33<05:13, 20.89s/it, R0|SeizeIT2|sub-005|test]

  R0/train/SeizeIT2/sub-005: 104 janelas (pré=52, inter=52)

Extração:  96%|███████████████████████████████▋ | 311/324 [3:16:15<04:30, 20.80s/it, R0|SeizeIT2|sub-006|test]

  R0/train/SeizeIT2/sub-006: 52 janelas (pré=26, inter=26)

Extração:  97%|███████████████████████████████▉ | 313/324 [3:17:27<05:12, 28.40s/it, R0|SeizeIT2|sub-007|test]

  R0/train/SeizeIT2/sub-007: 106 janelas (pré=53, inter=53)

Extração:  97%|████████████████████████████████ | 315/324 [3:19:14<05:57, 39.76s/it, R0|SeizeIT2|sub-008|test]

  R0/train/SeizeIT2/sub-008: 106 janelas (pré=53, inter=53)

Extração:  98%|████████████████████████████████▎| 317/324 [3:20:48<04:49, 41.39s/it, R0|SeizeIT2|sub-009|test]

  R0/train/SeizeIT2/sub-009: 52 janelas (pré=26, inter=26)

Extração:  98%|████████████████████████████████▍| 319/324 [3:22:15<03:31, 42.34s/it, R0|SeizeIT2|sub-010|test]

  R0/train/SeizeIT2/sub-010: 52 janelas (pré=26, inter=26)

Extração:  99%|████████████████████████████████▋| 321/324 [3:24:15<02:31, 50.35s/it, R0|SeizeIT2|sub-011|test]

  R0/train/SeizeIT2/sub-011: 156 janelas (pré=78, inter=78)

Extração: 100%|████████████████████████████████▉| 323/324 [3:26:10<00:51, 51.00s/it, R0|SeizeIT2|sub-012|test]

  R0/train/SeizeIT2/sub-012: 160 janelas (pré=80, inter=80)

Extração: 100%|█████████████████████████████████| 324/324 [3:26:58<00:00, 38.33s/it, R0|SeizeIT2|sub-012|test]

Extração concluída: 324 gravados | 0 excluídos.

## 6. Resumo e exclusões

In [7]:
if STATS:
    df_stats = pd.DataFrame(STATS)
    print('Treino (balanceado 1:1) por dataset e nível:')
    tr = df_stats[df_stats['mode'] == 'train'].groupby(['level', 'dataset']).agg(
        pacientes=('patient', 'count'), janelas=('n_total', 'sum'),
        pre=('n_pre', 'sum'), inter=('n_inter', 'sum')).reset_index()
    ipd.display(tr)
    print('\nTeste (distribuição natural) por dataset e nível:')
    te = df_stats[df_stats['mode'] == 'test'].groupby(['level', 'dataset']).agg(
        pacientes=('patient', 'count'), janelas=('n_total', 'sum'),
        pre=('n_pre', 'sum'), inter=('n_inter', 'sum')).reset_index()
    te['razao_real'] = (te['inter'] / te['pre']).round(1)
    ipd.display(te)
    df_stats.to_csv(os.path.join(LOG_DIR, 'features_stats.csv'), index=False)

if EXCLUSION_LOG:
    df_exc = pd.DataFrame(EXCLUSION_LOG)
    print(f'\nExclusões: {len(df_exc)}')
    ipd.display(df_exc)
    df_exc.to_csv(os.path.join(LOG_DIR, 'exclusoes_nb3.csv'), index=False)

print('\nExtração concluída. Próximo: Notebook 3.5 (verificação) e Notebook 4 (cenários).')

Treino (balanceado 1:1) por dataset e nível:

   level   dataset  pacientes  janelas   pre  inter
0     R0    CHBMIT         12     3698  1849   1849
1     R0  Mendeley          6     1597   870    727
2     R0  SeizeIT2         12     2012  1006   1006
3     R0     Siena         12     1870   935    935
4     R1    CHBMIT         12     3698  1849   1849
5     R1  Mendeley          6     1597   870    727
6     R1     Siena         12     1870   935    935
7     R2    CHBMIT         12     3698  1849   1849
8     R2  Mendeley          6     1597   870    727
9     R2     Siena         12     1870   935    935
10    R3    CHBMIT         12     3698  1849   1849
11    R3  Mendeley          6     1597   870    727
12    R3     Siena         12     1870   935    935
13    R5    CHBMIT         12     3698  1849   1849
14    R5  Mendeley          6     1597   870    727
15    R5     Siena         12     1870   935    935

Teste (distribuição natural) por dataset e nível:

   level   dataset  pacientes  janelas   pre   inter  razao_real
0     R0    CHBMIT         12    50718  3689   47029        12.7
1     R0  Mendeley          6     4402  1740    2662         1.5
2     R0  SeizeIT2         12   194740  2019  192721        95.5
3     R0     Siena         12    17471  1866   15605         8.4
4     R1    CHBMIT         12    50718  3689   47029        12.7
5     R1  Mendeley          6     4402  1740    2662         1.5
6     R1     Siena         12    17471  1866   15605         8.4
7     R2    CHBMIT         12    50718  3689   47029        12.7
8     R2  Mendeley          6     4402  1740    2662         1.5
9     R2     Siena         12    17471  1866   15605         8.4
10    R3    CHBMIT         12    50718  3689   47029        12.7
11    R3  Mendeley          6     4402  1740    2662         1.5
12    R3     Siena         12    17471  1866   15605         8.4
13    R5    CHBMIT         12    50718  3689   47029        12.7
14    R5  Mendeley          6     4402  1740    2662         1.5
15    R5     Siena         12    17471  1866   15605         8.4

Extração concluída. Próximo: Notebook 3.5 (verificação) e Notebook 4 (cenários).